Repository asyncapi/asyncapi-react, pull requests merged in 2022-07, with the labels that each got.

#614 fix: define react and react-dom as peerDependencies
  library/package.json
Labels: bug, dependencies, ready-to-merge

#620 feat: add deep collapse button in schema component
  library/package-lock.json
  library/package.json
  library/src/components/CollapseButton.tsx
  library/src/components/Schema.tsx
  library/src/containers/Messages/MessageExample.tsx
Labels: bug, enhancement

#629 docs: update the command to install the component
  README.md
  docs/usage/angular.md
  docs/usage/nextjs.md
  docs/usage/standalone-bundle.md
  docs/usage/vue.md
  docs/usage/web-component.md
Labels: ready-to-merge
