Repository asyncapi/asyncapi-react, pull requests merged in 2022-04, with the labels that each got.

#569 fix: bump dependencies in package-lock files
  library/package-lock.json
  package-lock.json
  playground/package-lock.json
  web-component/package-lock.json
Labels: ready-to-merge

#571 fix: update dependencies in component and web-component
  package-lock.json
  web-component/package-lock.json
Labels: dependencies, ready-to-merge

#577 fix: updated openapi-sampler to resolve security vulnerability CVE-20…
  library/package-lock.json
  library/package.json
Labels: ready-to-merge

#580 fix: bump dependencies
  library/package-lock.json
  library/package.json
Labels: dependencies, ready-to-merge

#584 feat: support AsyncAPI 2.4.0
  library/package-lock.json
  library/package.json
  library/src/containers/Messages/Message.tsx
  library/src/containers/Operations/Operation.tsx
  library/src/containers/Servers/Security.tsx
  library/src/containers/Servers/Server.tsx
  playground/src/specs/streetlights.ts
Labels: enhancement

#590 fix: add fallback for null parameter's schema
  library/src/helpers/__tests__/schema.test.ts
  library/src/helpers/schema.ts
Labels: bug
