Repository asyncapi/asyncapi-react, pull requests merged in 2022-01, with the labels that each got.

#502 fix: render empty extensions and bindings
  library/src/components/Bindings.tsx
  library/src/components/Extensions.tsx
  library/src/components/__tests__/Bindings.test.tsx
  library/src/components/__tests__/Extensions.test.tsx
  library/src/helpers/__tests__/schema.test.ts
  library/src/helpers/schema.ts
Labels: bug

#511 fix: do not download schemaUrl several times in a short time in the web-component
  library/src/types.ts
  web-component/src/AsyncApiWebComponent.tsx
Labels: bug, area/library, ready-to-merge

#522 fix: updated marked patch
  library/package.json
  library/src/helpers/marked.ts
Labels: ready-to-merge

#540 feat: support 2.3.0 version of spec
  library/package-lock.json
  library/package.json
Labels: ready-to-merge
