Repository asyncapi/asyncapi-react, pull requests merged in 2022-09, with the labels that each got.

#632 feat: add config options to override pub sub label text
  docs/configuration/config-modification.md
  library/src/config/config.ts
  library/src/config/default.ts
  library/src/constants.ts
  library/src/containers/Operations/Operation.tsx
  library/src/containers/Sidebar/Sidebar.tsx
  package.json
Labels: ready-to-merge

#638 fix: render default,const boolean values in Schema component
  library/src/components/Schema.tsx
  library/src/components/__tests__/Schema.test.tsx
  library/src/helpers/__tests__/schema.test.ts
  library/src/helpers/schema.ts
Labels: bug

#647 feat: support AsyncAPI 2.5.0
  library/package-lock.json
  library/package.json
  library/src/containers/Servers/Server.tsx
  playground/src/specs/streetlights.ts
Labels: enhancement, ready-to-merge
